version: '3'
services:
  app:
    build: .
    container_name: giftstock
    volumes:
      - ./:/home/giftstock

    ports:
      - "8030:8088"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3316:3316"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: giftstock
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret

volumes:
  db_data: {}